var data = [
    { code: "AU481", agent: "1TURISMO ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU482", agent: "55 DESTINOS VIAGENS ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU483", agent: "Abratour Tour Operator", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU484", agent: "Abreutur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU485", agent: "Agaxtur ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU486", agent: "Agaxtur Premium ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU487", agent: "Ambiental Tur ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU488", agent: "Ancoradouro ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU489", agent: "Aniyami DMC", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU490", agent: "AIT Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU491", agent: "Asia Total ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU492", agent: "Athos Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU493", agent: "Atlantic Connection ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU494", agent: "Aurora Eco", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU495", agent: "Bauer Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU496", agent: "Belvitur ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU497", agent: "Boreal Turismo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU498", agent: "Bon Voyage Tur ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU499", agent: "Blanctour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU500", agent: "Blend Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU501", agent: "Brisasol", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU502", agent: "BRT Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU503", agent: "BTG ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU504", agent: "BWT Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU505", agent: "Carlson Wagonlit ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU506", agent: "Century Travel Tour Operator", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU507", agent: "CNT Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU508", agent: "CT Operadora- Signature", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU509", agent: "CIA ECO", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU510", agent: "CIA MARITIMA", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU511", agent: "GOYA ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU512", agent: "Conquest Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU513", agent: "CVC Corp", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU514", agent: "Diversa Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU515", agent: "Elemental Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU516", agent: "Embarque with Us", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU517", agent: "Europlus", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU518", agent: "Formula Turismo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU519", agent: "FREEWAY VIAGENS ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU520", agent: "Françatur RJ ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU521", agent: "Fui Viagens RJ ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU522", agent: "FVO Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU523", agent: "GreenTrip Operator ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU524", agent: "Gladtur ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU525", agent: "CVC ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU526", agent: "MMT GAPNET ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU527", agent: "FLOT VIAGENS ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU528", agent: "FLYTOUR VIAGENS ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU529", agent: "Flytour MMT Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU530", agent: "Kangaroo Tours ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU531", agent: "Kangaroo Rio ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU532", agent: "Huapi World Tour Operator", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU533", agent: "Kangaroo Sul - Curitiba ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU534", agent: "Interep ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU535", agent: "Interpoint", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU536", agent: "Intravel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU537", agent: "Investur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU538", agent: "INCOMUM ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU539", agent: "Inti Experience", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU540", agent: "Interpoint", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU541", agent: "Jet Tour Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU542", agent: "Judy & Associates", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU543", agent: "JVS Operadora  - NEW", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU544", agent: "JUSTTUR ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU545", agent: "Keith Prowse / The One Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU546", agent: "Klas Viagens e Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU547", agent: "Latitudes ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU548", agent: "LAGETUR", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU549", agent: "L’Espace", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU550", agent: "LINK PREMIUM ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU551", agent: "Litoral Verde", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU552", agent: "Magic Way ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU553", agent: "Mandala Tours ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU554", agent: "MAK TOUR", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU555", agent: "Marsans Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU556", agent: "Max Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU557", agent: "Master Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU558", agent: "Mdart ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU559", agent: "MERCATUR PREMIUM", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU560", agent: "MGM Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU561", agent: "MG3 Operadora E Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU562", agent: "Milessis ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU563", agent: "MK TRAVEL ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU564", agent: "Monark Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU565", agent: "Moinho Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU566", agent: "MUNDUS", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU567", agent: "MULTIDESTINOS", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU568", agent: "New Age", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU569", agent: "NEWMON ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU570", agent: "NEW IT CLUB ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU571", agent: "Nivana", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU572", agent: "Nova Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU573", agent: "Nova Safari Tours", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU574", agent: "OIKOS TRAVEL", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU575", agent: "Orinter Tour & Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU576", agent: "Orion Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU577", agent: "Operadora Vojitour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU578", agent: "Partenon Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU579", agent: "Personal Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU580", agent: "Personal Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU581", agent: "Portfolio Travel  ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU582", agent: "Prime Tour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU583", agent: "QUEENSBERRY", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU584", agent: "RAIDHO - NEW", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU585", agent: "RCA Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU586", agent: "Raidho / Sonhos A2 ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU587", agent: "Riva Turismo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU588", agent: "RZ Turismo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU589", agent: "Safari 365 ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU590", agent: "Salvador Lembo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU591", agent: "Schultz", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU592", agent: "Selections ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU593", agent: "Sete Mares Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU594", agent: "Snowtime ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU595", agent: "SOUL TRAVELER ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU596", agent: "Tablet Tours ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU597", agent: "Taks Tour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU598", agent: "TERRAMUNDI ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU599", agent: "Teresa Perez ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU600", agent: "Tourlines", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU601", agent: "Trade Tours", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU602", agent: "Travel Place", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU603", agent: "Travel Workers Agência Boutique ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU604", agent: "Transamerica Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU605", agent: "Transmundi", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU606", agent: "Trend Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU607", agent: "TGK Tour Operator", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU608", agent: "Trade Tours ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU609", agent: "Travel.com ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU610", agent: "Travely ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU611", agent: "Trend Operadora", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU612", agent: "Trip4U ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU613", agent: "TT OPERADORA  / Lufthansa CC", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU614", agent: "Turisplan", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU615", agent: "Uniglobe / Megtur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU616", agent: "Uneworld ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU617", agent: "Vectra Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU618", agent: "Venturas", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU619", agent: "Venturo Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU620", agent: "VIAGENS BY DELBIANCO", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU621", agent: "Viajar Operadora ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU622", agent: "VIAGENS & CIA ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU623", agent: "VIAGENS INCOMUM", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU624", agent: "Visual turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU625", agent: "Viva Terra", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU626", agent: "Voe Plus ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU627", agent: "Raidho", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU628", agent: "TUI Brasil", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU629", agent: "WT Tours ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU630", agent: "Vita Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU631", agent: "Voyager Club", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU632", agent: "Adventure Club", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU633", agent: "Adnet Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU634", agent: "Adventure Weekend", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU635", agent: "AGÊNCIA BOUTIQUE LUXURY ID", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU636", agent: "Alessandra Peres Consultoria em Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU637", agent: "Alterna tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU638", agent: "Ana Terra Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU639", agent: "Angel Travel Advisor", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU640", agent: "Anita Fisher", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU641", agent: "Apex Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU642", agent: "Ativa Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU643", agent: "Atlanta Tour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU644", agent: "Attuale Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU645", agent: "Ares Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU646", agent: "Autêntica Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU647", agent: "Bini Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU648", agent: "Bahia Bella", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU649", agent: "Baritur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU650", agent: "Bol", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU651", agent: "Bozó Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU652", agent: "Blend", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU653", agent: "Blue Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU654", agent: "Bluepapayatour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU655", agent: "Brasilia Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU656", agent: "Brazil concepts", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU657", agent: "Braga Travel Consulting ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU658", agent: "Bittar Turismo e Viagens LTDA", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU659", agent: "Camilla Mattar Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU660", agent: "Carol Moretti Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU661", agent: "Carona Cultural", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU662", agent: "Cays Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU663", agent: "Central Logística ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU664", agent: "Clan Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU665", agent: "Celebrare Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU666", agent: "Ciatur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU667", agent: "Cinqtours", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU668", agent: "Costa Brava", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU669", agent: "Conceito Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU670", agent: "DCTur Porto Alegre", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU671", agent: "Details Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU672", agent: "Destaque Turismo ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU673", agent: "DONATO VIAGENS", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU674", agent: "D. Tabuso", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU675", agent: "Diferencial Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU676", agent: "Soul Dreams Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU677", agent: "Specialité Turimso", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU678", agent: "Esmeralda Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU679", agent: "Escapadas Online", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU680", agent: "Escape Travel Advisors", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU681", agent: "ES Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU682", agent: "Estação Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU683", agent: "Fernanda Maisonnave Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU684", agent: "Free to Be Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU685", agent: "Fly Me Boutique", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU686", agent: "Flap Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU687", agent: "Flytour Uberaba", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU688", agent: "FOB Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU689", agent: "Fredtour", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU690", agent: "FVO Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU691", agent: "Gentil Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU692", agent: "Go Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU693", agent: "Global Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU694", agent: "GVTN Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU695", agent: "GW Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU696", agent: "Hedging Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU697", agent: "Handmade Vacations", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU698", agent: "Ivigens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU699", agent: "Investur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU700", agent: "Just Tur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU701", agent: "Jet Set Viagens e Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU702", agent: "Jdegraf", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU703", agent: "Kuryala", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU704", agent: "Master Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU705", agent: "MY TRAVEL DNA", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU706", agent: "MZ Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU707", agent: "NEXT2TRAVEL", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU708", agent: "LET Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU709", agent: "LF viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU710", agent: "Lili Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU711", agent: "Lotustravel Viagens e Turismo Ltda", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU712", agent: "LTN Brazil", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU713", agent: "Leroy Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU714", agent: "Lumi Viagen", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU715", agent: "Luxury ID", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU716", agent: "Luve Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU717", agent: "Milah Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU718", agent: "My Travel DNA", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU719", agent: "Mappa Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU720", agent: "MALABASS", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU721", agent: "Mali Travel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU722", agent: "Massari Travel & Experience", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU723", agent: "Menton Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU724", agent: "Nahas Tur Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU725", agent: "Next 2 Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU726", agent: "Numatur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU727", agent: "Oca Consultoria", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU728", agent: "OP Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU729", agent: "O Vianjante Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU730", agent: "OWT Boutique Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU731", agent: "PHD Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU732", agent: "Paraíso Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU733", agent: "Plan Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU734", agent: "Plantel Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU735", agent: "Portobello Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU736", agent: "Porto Brasil", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU737", agent: "Por Claudia Estrella", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU738", agent: "Premier Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU739", agent: "Romy Viagens", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU740", agent: "Ruy Lage", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU741", agent: "SafeTur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU742", agent: "SAVVY TOUR", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU743", agent: "Scan Suisse Viagens e Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU744", agent: "Sensations Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU745", agent: "Sete Mares Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU746", agent: "Siga Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU747", agent: "Soldeocana", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU748", agent: "Socaltur Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU749", agent: "Shilton", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU750", agent: "Stancatti Viagens e Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU751", agent: "Superférias", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU752", agent: "SURFTRIP TOUR", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU753", agent: "Tathiana Almeida Viagens Especiais", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU754", agent: "Taste The World", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU755", agent: "The Travel Experience", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU756", agent: "Terranova", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU757", agent: "Tortola", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU758", agent: "Tailor Made Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU759", agent: "TM travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU760", agent: "Top Travellers", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU761", agent: "Transamericatur", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU762", agent: "Trotamundo Viagens ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU763", agent: "Tropical Turismo Intercambio", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU764", agent: "Turisplan", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU765", agent: "TZ Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU766", agent: "Kubrusly Travel Center", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU767", agent: "Viana Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU768", agent: "Via Moreale Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU769", agent: "Viaje Global", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU770", agent: "Vendra Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU771", agent: "Vete Brasil", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU772", agent: "ViaBR", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU773", agent: "WHG Turismo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU774", agent: "Viabellu", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU775", agent: "Villa Mundo", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU776", agent: "Xtravel ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU777", agent: "Vtripper (Startup)", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU778", agent: "We Tours", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU779", agent: "Welcome Trips ", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU780", agent: "Your way Travel", nation: "Brazil", landing: 10, acc: 12 },
    { code: "AU781", agent: "Plan My Holidays ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU782", agent: "Holidays Boutique ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU783", agent: "the Ark Travel Group", nation: "Indian", landing: 12, acc: 12 },
    { code: "AU784", agent: "TBO.com", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU785", agent: "Culture Holiday", nation: "Indian", landing: 11, acc: 11 },
    { code: "AU786", agent: "Crosswoods happy holidays ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU787", agent: "Travstarz", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU788", agent: "Kushal Holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU789", agent: "Carnation Travels", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU790", agent: "Royal Trip Maker", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU791", agent: "Antilog Vacations", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU792", agent: "Sygnus Travels ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU793", agent: "IRI iFly Holidays Travel Advicer", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU794", agent: "Black Swan ", nation: "Indian", landing: 11, acc: 11 },
    { code: "AU795", agent: "The Tour Diary ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU796", agent: "RSA TRAVEL GROUP ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU797", agent: "Unique Tours & Travels ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU798", agent: "Gujral  Tours & Travels ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU799", agent: "Travels 2020   ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU800", agent: "Fly Me Trips", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU801", agent: "Concept Holidayz Planner", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU802", agent: "Smart Holiday Shop", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU803", agent: "Banjare Holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU804", agent: "WMTC", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU805", agent: "Ondgo Travels ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU806", agent: "JTB India Pvt. Ltd. ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU807", agent: "Club 7 Holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU808", agent: "VAYUDOOT", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU809", agent: "My Dream Holiday", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU810", agent: "Excursia", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU811", agent: "True blue travel", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU812", agent: "Namaah Travel", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU813", agent: "Emiror holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU814", agent: "Offbeat Travel", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU815", agent: "Emiror holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU816", agent: "The Holiday Store", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU817", agent: "Travoinspire Global Pvt Ltd ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU818", agent: "VATANS TRAVEL AND TOURS", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU819", agent: "Unhotel", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU820", agent: "My Travelogue", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU821", agent: "Katara Holidays", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU822", agent: "Safalya Holidays ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU823", agent: "AATREYA TOURS & TRAVELS ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU824", agent: "SOTC", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU825", agent: "Prince Stelaa Tourism LLC ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU826", agent: "Itvara Hospitality ", nation: "Indian", landing: 10, acc: 10 },
    { code: "AU827", agent: "Didi Travel ", nation: "Kenya", landing: 12, acc: 12 },
    { code: "AU828", agent: "BEXCLUSIVE", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU829", agent: "OasisTravel", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU830", agent: "All The Way Travel", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU831", agent: "BEST TRAVEL BELÉM", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU832", agent: "WTS VIAGENS", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU833", agent: "VIAGENS TEMPO", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU834", agent: "QUADRANTE", nation: "PORTUGAL", landing: 10, acc: 12 },
    { code: "AU835", agent: "Gap Travel", nation: "South African", landing: 10, acc: 10 },
    { code: "AU836", agent: "APS Travel ", nation: "Thailand ", landing: 10, acc: 10 },
    { code: "AU837", agent: "ASIAIZA VIAJES", nation: "Thailand ", landing: 10, acc: 10 }
]
ObjectIdGrender = (m = Math, d = Date, h = 16, s = s => m.floor(s).toString(h)) => s(d.now() / 1000) + ' '.repeat(h).replace(/./g, () => s(m.random() * h))
function uuidv4() {
    try {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
    catch (err) {
        throw "LibService: uuidv4() Exception";
    }
}
data.forEach(vl => {
    let _id = ObjectIdGrender()
    let agent = {
        isImport: true,
        "_id": ObjectId(_id),
        "ref": "",
        "agencyTitle": null,
        "name": vl.agent,
        "code": vl.code,
        "agid": "",
        "email": null,
        "country": vl.nation,
        "address": "",
        "adtel": "",
        "booker_email": "",
        "agencygroup": "",
        "aconsortia": "",
        "procodes": null,
        "isActive": true,
        "contacts": []
    }
    let procodes = {
        isImport: true,
        "nation": "vn",
        "md5code": uuidv4(),
        "gents_onlines": ObjectId(_id),
        "period": [
            {
                "p_begin": new Date("01/01/2024 14:00:00"),
                "p_end": new Date("12/31/2024 14:00:00"),
                "p_htpro": vl.acc,
                "p_tourpro": vl.landing,
                "p_airfare": 0
            }
        ],
        "language": [
            "5eb4c31759281b9ace72f834",
            "5eb4c31759281b9ace72f83a",
            "5eb4c31d59281b9ace72f884"
        ],
        "cname": "Andrew Dao Anh Son",
        "cmarket": "WW",
        "ccurrency": "USD",
        "agencyType": "Wholesale",
        "active": true,
        "online": true,
        "cemail": "son@auroratravel.asia",
    }
    //print(procodes)
    db.getCollection("gents_onlines").insert(agent);
    db.getCollection("procodes").insert(procodes);
});